export const STATUS_CHANGE = 'STATUS_CHANGE';

export const WELCOME = 'WELCOME';

export const WRITE_MESSAGE = 'WRITE_MESSAGE';

export const START_SEND_MESSAGE = 'START_SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESSFUL = 'SEND_MESSAGE_SUCCESSFUL';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

export const START_API_REQUEST = 'START_API_REQUEST';
export const API_REQUEST_SUCCESSFUL = 'API_REQUEST_SUCCESSFUL';
export const API_REQUEST_FAILED = 'API_REQUEST_FAILED';
