export const WELCOME = 'WELCOME';

export const WRITE_MESSAGE = 'WRITE_MESSAGE';

export const START_SEND_MESSAGE = 'START_SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESSFUL = 'SEND_MESSAGE_SUCCESSFUL';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';
